### ISSUE TITLE
Existing settings don't seem to be retained

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [winneon/hypersixteen#2]
So, I've added `hypersixteen` to my `.hyper.js`,

```js
  // border color (window, tabs)
  borderColor: '#FFCC66',

  // ...

  plugins: [ "hypersixteen" ],
```

… and although the code [seems to](https://github.com/winneon/hypersixteen/blob/6c4409ea/src/HyperSixteen.js#L33-L39) offer preference to *existing* configuration-values,

```es6
    let backgroundColor = config.backgroundColor || base16.base00
    let darkBackgroundColor = this.shade(backgroundColor, -0.4)
    let foregroundColor = config.foregroundColor || ansi.white
    let cursorColor = config.cursorColor || ansi.white
    let borderColor = config.borderColor || darkBackgroundColor
```

… my Hyper windows don't have a yellow border.

What am I doing wrong here?

**Comment by win0na** [comment]
You weren't doing anything wrong, I forgot to push the changes to a new npm version. This should be fixed in `v1.0.4`.
